### ISSUE TITLE
Search bar doesn't close after clicking the "X" button

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/website#366] opened 2019-07-01 07:58 UTC
**Description**

Once the search bar is open, you can't close it using the "X" button.

![image](https://user-images.githubusercontent.com/29116492/60419979-dcc21100-9be6-11e9-8617-44e94ce3ea0a.png)

**Expected result**

Closes when I click "X". 

**Actual result**

Closes only when I click outside of the search bar. 

**Steps to reproduce**

Open kyma-project.io in Chrome (75.0.3770.100) or Safari, click the magnifying glass icon, try closing the search bar with "X". 

**Troubleshooting**

?

**Comment by magicmatatjahu** [comment] 2019-07-04 06:15
@tomekpapiernik Hello my favourite contributor of website (or rather favourite issues creator 😄). This is not a bug, but "X" button clear input search, not close field, so I will close this issue.

**Closed by magicmatatjahu** 2019-07-04 06:15 UTC
Labels: bug
