### ISSUE TITLE
Issue with rendering docs for CLI 1.17

### ISSUE THREAD

**Issue by kazydek** [kyma-project/website#658] opened 2020-12-17 15:43 UTC
**Description**

Docs for [CLI 1.17](https://kyma-project.io/docs/cli/) are not rendered on the website for some reason.

**Actual result**

<img width="266" alt="Screen Shot 2020-12-17 at 15 42 06" src="https://user-images.githubusercontent.com/40655785/102509328-b61bc280-4086-11eb-820a-d9112b7a3d1e.png">

**Comment by klaudiagrz** [comment] 2020-12-18 14:11
I'm also not sure 1.16 should be marked as a pre-release:
<img width="278" alt="Screen Shot 2020-12-18 at 15 10 53" src="https://user-images.githubusercontent.com/35192450/102623756-4ae3f600-4143-11eb-938e-779d3e2e18b8.png">

**Comment by Disper** [comment] 2020-12-21 10:55
@klaudiagrz 1.16 should be marked as pre-release.

**Comment by aerfio** [comment] 2020-12-21 14:25
The fact that it only showed latest 1 version was _a feature not a bug_ 😛 , but I've changed it to show latest _3_ versions. Fixed in #662

**Closed by aerfio** 2020-12-21 14:25 UTC
Labels: area/documentation, bug
