### ISSUE TITLE
In a nutshell Component for Kyma Homepage

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#632] opened 2020-09-16 12:00 UTC
**Description**

As Mathew and Sebastian ([personas](https://github.com/kyma-project/community/blob/master/manifesto/personas.md)) I would like to understand at a glance, how is kyma working, and using a high level diagram is the best way to Visualize this

**Acceptance Criteria**

- The component follows the designs attached ( Desktop and mobile ) and responsive behaviour ( see wide screen version for background stretching )
- The text is SEO relevant and is SSR
- we are using minimised SVGs as background graphics. The background is 100% width of the viewport, and stretches horizontally fitting the viewport
- There is no Get IT On Github button
- We use a dummy svg for the diagram, but this scales up/down in responsive way
- Mobile version has button opening the diagram in new tab in full screen                                                                                                   

**Attachments**
![image](https://user-images.githubusercontent.com/478866/93333869-46e2c800-f824-11ea-9130-98c914951c0f.png)
![image](https://user-images.githubusercontent.com/478866/93333927-5b26c500-f824-11ea-82a7-8896d88357fa.png)
![image](https://user-images.githubusercontent.com/478866/93896563-5913a900-fcf1-11ea-8712-c908060c904a.png)

**Comment by pPrecel** [comment] 2021-04-12 06:17
[This PR](https://github.com/kyma-project/website/pull/691) is merged but the issue is still in progress because we need to refill SVGs

**Comment by kwiatekus** [comment] 2021-08-30 12:35
This component is available on the main branch

**Closed** 2021-08-30 12:35 UTC
Labels: area/community
