### ISSUE TITLE
Inaccurate links in the sidebars

### ISSUE THREAD

**Issue by franpog859** [kyma-project/website#479] opened 2019-10-24 08:29 UTC
**Description**

Hey! When I go to the [Kyma documentation](https://kyma-project.io/docs/) and click on for example the [Console Configuration link](https://kyma-project.io/docs/components/console/#configuration-configuration) in the sidebar, site scrolls down but not to the Console Configuration section. At least not every time

**Expected result**

Links scroll the site to the sections accurately every time

**Actual result**

They do but not every time

**Steps to reproduce**

To reproduce this bug go to the site and click on the links a few times. Try also the incognito window, with slower internet and after deletion of cached images. I use Chrome `Version 76.0.3809.132 (Official Build) (64-bit)` and macOS Mojave `Version 10.14.5`

**Troubleshooting**

I found that other websites was dealing with similar issues. Take a look at [their solutions](https://github.com/Kong/kuma-website/issues/46). It may be helpful while working on the fix!

**Comment by derberg** [comment] 2019-10-25 08:51
This is caused by a huge 1mb header that loads with delay, this is why you are sometimes moved in the UI to some other section. I till be fixed today, or monday once we merge all the changes to the landing page we are working on now. Header will be 2kb now. Closing for now as like I wrote we handle it in another ticket

**Comment by franpog859** [comment] 2020-02-07 09:22
Hey! The bug still occurs. This time I wanted to navigate to [Director description](https://kyma-project.io/docs/components/compass/#architecture-components-director) and the site brought me somewhere around the [Cockpit description](https://kyma-project.io/docs/components/compass/#architecture-components-cockpit). It's not a big deal but it's quite annoying

**Comment by franpog859** [comment] 2020-04-01 08:08
Hey! The bug still occurs. This time [troubleshooting](https://kyma-project.io/docs/components/service-mesh#troubleshooting-connection-refused-errors-after-upgrade) brought me in the middle of some huge bash example below [this part](https://kyma-project.io/docs/components/service-mesh#configuration-service-mesh-production-profile-use-the-production-profile). It's annoying when you search for something and the link is that inaccurate. The menu on the right sidebar wasn't even toggled properly and I wasn't seeing the part I searched for. I talked with other people and they find it annoying too

**Comment by magicmatatjahu** [comment] 2020-04-26 19:25
@franpog859 Hi and sorry for that late response. We had hope that we resolved issue by fixing header in docs view, but we see that problem still occurs. The main culprits are images. If you go to, for example, root docs topic -`Kyma`, then your browser load a lot of html code and of course images. The browsers don't have native support (as I know) for checking what height the image will have on loading, but they have after fetching, so you go to docs, then browser load html, with image tags with 0px height, redirect you to appropriate id, and then browser load image data and your browser jumps up because the amount of documentation (by height of fetches images) increases.

Already we have some little timeout in first redirection to some docs id, but we see that the timeout value is not sufficient. The only hope is to deliver the height of the image via css after loading the page (for some placeholder), but I don't know when we will find the time to fix that bug :)

**Comment by magicmatatjahu** [comment] 2020-06-03 07:57
Fixed by https://github.com/kyma-project/website/pull/563

**Closed by magicmatatjahu** 2020-06-03 07:57 UTC
Labels: area/community, area/quality, bug
